# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PostgreSQL
        uses: mirromutth/postgresql-action@v1.1
        with:
          postgres version: 'postgres:16-alpine3.19'
          postgres database: 'dev_jrtb_db'
          postgres user: 'postgres'
          postgres password: 'postgres'
      - name: Set up JDK 1.18
        uses: actions/setup-java@v1
        with:
          java-version: 1.18
      - name: Build with Maven
        run: mvn -B package --file pom.xml

